document.write("<script type=\"text\/javascript\"");
document.write("  src=\"https:\/\/shanechern.github.io\/javascripts\/latex\/LaTeXMathML.js\">");
document.write("  <\/script>");
document.write("    ");
document.write("  <script src=\"https:\/\/use.fontawesome.com\/baff6f55f5.js\"><\/script>");
document.write("    <meta charset=\"utf-8\">");
document.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
document.write("    <title>Shane Chern<\/title>");
document.write("    <link rel=\"icon\" type=\"image\/svg\" href=\"icon\/DAL.svg\" \/>");
document.write("");
document.write("    <link rel=\"stylesheet\" href=\"stylesheets\/styles.css\">");
document.write("    <link rel=\"stylesheet\" href=\"stylesheets\/github-light.css\">");
document.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=yes\">");
document.write("    <!--[if lt IE 9]>");
document.write("    <script src=\"\/\/html5shiv.googlecode.com\/svn\/trunk\/html5.js\"><\/script>");
document.write("    <![endif]-->");
document.write("");
document.write("    <script>");
document.write("      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){");
document.write("      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),");
document.write("      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)");
document.write("      })(window,document,'script','https:\/\/www.google-analytics.com\/analytics.js','ga');");
document.write("");
document.write("      ga('create', 'UA-29643011-3', 'auto');");
document.write("      ga('send', 'pageview');");
document.write("    <\/script>");
document.write("");
document.write("    <!-- For all browsers -->");
document.write("    <link rel=\"stylesheet\" href=\"assets\/css\/academicons.min.css\"\/>");
document.write("    <link rel=\"stylesheet\" href=\"assets\/css\/academicons.css\"\/>");
document.write("    ");
document.write("    <style>");
document.write("      button.accordion {");
document.write("      font:14px\/1.5 Lato, \"Helvetica Neue\", Helvetica, Arial, sans-serif;");
document.write("      cursor: pointer;");
document.write("      padding: 0px;");
document.write("      border: none;");
document.write("      text-align: left;");
document.write("      outline: none;");
document.write("      font-size: 100%;");
document.write("      transition: 0.3s;");
document.write("      background-color: #f8f8f8;");
document.write("      }");
document.write("      button.accordion.active, button.accordion:hover {");
document.write("      background-color: #f8f8f8;");
document.write("      }");
document.write("      button.accordion:after {");
document.write("      content: \" [+] \";");
document.write("      font-size: 90%;");
document.write("      color:#777;");
document.write("      float: left;");
document.write("      margin-left: 1px;");
document.write("      }");
document.write("");
document.write("      button.accordion.active:after {");
document.write("      content: \" [\2212] \";");
document.write("      }");
document.write("      div.panel {");
document.write("      padding: 0 20px;");
document.write("      margin-top: 5px;");
document.write("      display: none;");
document.write("      background-color: white;");
document.write("      font-size: 100%;");
document.write("      }");
document.write("      div.panel.show {");
document.write("      display: block !important;");
document.write("      }");
document.write("      .social-row {");
document.write("        display: flex;");
document.write("        flex-wrap: wrap;");
document.write("        justify-content: space-between;");
document.write("      }");
document.write("    <\/style>");
